# permissions for end users to edit openshiftfyres.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshiftfyre-editor-role
rules:
- apiGroups:
  - clusters.ibm.com
  resources:
  - openshiftfyres
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clusters.ibm.com
  resources:
  - openshiftfyres/status
  verbs:
  - get
