# permissions for end users to view openshiftfyres.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshiftfyre-viewer-role
rules:
- apiGroups:
  - clusters.ibm.com
  resources:
  - openshiftfyres
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - clusters.ibm.com
  resources:
  - openshiftfyres/status
  verbs:
  - get
