# permissions for end users to edit openshiftclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshiftcluster-editor-role
rules:
- apiGroups:
  - fyre.ibm.com
  resources:
  - openshiftclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fyre.ibm.com
  resources:
  - openshiftclusters/status
  verbs:
  - get
