apiVersion: clusters.ibm.com/v1alpha1
kind: OpenShiftFyre
metadata:
  name: openshiftfyre-sample
spec:
  # Add fields here
  providerSecretRef: fyre-secret
  quotaType: "quick_burn"
  site: "svl"
  ocpVersion: "4.8.27"
  platform: "x"
  size: "medium"
  timeToLive: 1
