apiVersion: fyre.ibm.com/v1alpha1
kind: OpenShiftCluster
metadata:
  name: openshiftcluster-sample
spec:
  # Add fields here
  providerSecretRef: fyre-secret
  ocpVersion: "4.8.27"
  timeToLive: "1"
  size: "medium"
