---
- name: Provision new cluster
  block:

    - name: Provision new cluster
      no_log: true
      uri:
        url: 'https://ocpapi.svl.ibm.com/v1/ocp/'
        method: POST
        user: '{{ provider_username }}'
        password: '{{ provider_password }}'
        headers:
          "Content-Type": application/json
        force_basic_auth: yes
        validate_certs: no
        body: '{{ lookup("template","../templates/{{ quota_type }}.j2") }}'
        body_format: json
        status_code: 201
      register: new_cluster_result
      failed_when: false

    - debug:
        var: new_cluster_result

    - set_fact:
        cluster_id: 'unknown'
        cluster_name: '{{ new_cluster_result.json.cluster_name }}'
        cluster_status: 'unknown'
        cluster_username: 'unknown'
        cluster_password: 'unknown'
        cluster_apiserver: 'unknown'
      when: new_cluster_result.json.cluster_name is defined

  when:
    - (provider_username is defined) and (provider_username|length > 0)
    - (provider_password is defined) and (provider_password|length > 0)
    - (cluster_name is not defined) or (cluster_name|length == 0)

- name: Update cluster status
  operator_sdk.util.k8s_status:
    api_version: '{{ api_version }}'
    kind: '{{ kind }}'
    name: '{{ ansible_operator_meta.name }}'
    namespace: '{{ ansible_operator_meta.namespace }}'
    status:
      cluster:
        id: '{{ cluster_id | default ("unkown") }}'
        name: '{{ cluster_name }}'
        status: '{{ cluster_status | default ("unkown") }}'
        username: '{{ cluster_username | default ("unkown") }}'
        password: '{{ cluster_password | default ("unkown") }}'
        apiserver: '{{ cluster_apiserver | default ("unkown") }}'
  when: (cluster_name is defined) or (cluster_name|length > 0)

- name: Add cluster to Argo CD
  include_tasks: add-cluster-to-argocd.yml
  when: (argocd is defined) and (argocd.namespace is defined)
